# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9fdd6faf01413907fade07a886b6900d3a909f462070beb2a71509df6e7b7e0c548c4ae8dea3384abe30de446411e0fadc2d5d6711aa4fb0975067cd9b9e8283

test:
  secret_key_base: 40270e4da32c6f578f6ee1d4619cf22b652c316e66089dd2ada286e347820ed0aea9da3c8d9e38f96c6caab38884158400b44b5319c02fbd073444a9a3d6b41e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
